# Generated by Django 3.1.5 on 2021-02-04 08:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Expert'), (4, 'Operator')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=25)),
                ('component_lk_number', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
                ('department_desc', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_code', models.CharField(max_length=5)),
                ('shift_name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department')),
                ('user_design', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department')),
                ('user_design', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_number', models.CharField(max_length=12)),
                ('machine_description', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('operation_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.operations')),
            ],
        ),
        migrations.CreateModel(
            name='Laser_production',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=10)),
                ('component_lot_number', models.CharField(max_length=5)),
                ('component_quantity', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('component_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.components')),
                ('machine_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.machines')),
                ('shift_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.shifts')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department')),
                ('user_design', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user_design', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
