# Generated by Django 3.1.5 on 2021-02-08 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosch_production_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department'),
        ),
    ]
