# Generated by Django 3.1.5 on 2021-02-08 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosch_production_app', '0002_auto_20210208_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_design',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expert',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user_design',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laser_production',
            name='component_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.components'),
        ),
        migrations.AlterField(
            model_name='laser_production',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.machines'),
        ),
        migrations.AlterField(
            model_name='laser_production',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.shifts'),
        ),
        migrations.AlterField(
            model_name='machines',
            name='operation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.operations'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_design',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operator',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='user_design',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
