# Generated by Django 3.1.5 on 2021-02-08 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosch_production_app', '0003_auto_20210208_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bosch_production_app.department'),
        ),
    ]
