# Generated by Django 3.1.5 on 2021-02-08 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosch_production_app', '0005_auto_20210208_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bosch_production_app.department'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_design',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
