# Generated by Django 3.1.5 on 2021-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosch_production_app', '0006_auto_20210208_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
